ALTER TYPE "OralFluencyBehaviorType" ADD VALUE IF NOT EXISTS 'VOICE_HARDLY_AUDIBLE';
ALTER TYPE "OralFluencyBehaviorType" ADD VALUE IF NOT EXISTS 'FINGER_POINTING';
ALTER TYPE "OralFluencyBehaviorType" ADD VALUE IF NOT EXISTS 'LITTLE_OR_NO_ANALYSIS';
